name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: echo "Packages installed"

    - name: Run unit tests
      run: echo "Pass - 100, Fail - 0"

    - name: Build
      run: echo "Built files generated"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
    - name: Deploy to staging
      run: echo "Deployed onto Staging"
      # Add your deployment steps here